// Auto-generated by scripts/generate-build-log.mjs — do not edit.
// The Iteration Forge floor renders this as the forge's output.
export interface BuildLogEntry { sha: string; date: string; subject: string }
export const BUILD_LOG: BuildLogEntry[] = [
  {
    "sha": "db05037",
    "date": "2026-08-09",
    "subject": "The Lathe becomes a foundry city: real melt, real skyline, a real shift"
  },
  {
    "sha": "f35f4e6",
    "date": "2026-08-09",
    "subject": "Add blog post: You Can Build Anything. That Is the Problem."
  },
  {
    "sha": "b9e6d5d",
    "date": "2026-08-09",
    "subject": "Arclight comes alive: the agents roam, work, and meet"
  },
  {
    "sha": "7829547",
    "date": "2026-08-09",
    "subject": "Arclight joins the mainland: causeways, real water, rooftops and doors"
  },
  {
    "sha": "148ebca",
    "date": "2026-08-09",
    "subject": "Arclight gets depth: sky dome, distant skyline, low camera, lit windows"
  },
  {
    "sha": "5b8ff35",
    "date": "2026-08-09",
    "subject": "Arclight: the Foundry, Mint and Custom House join the surface pass"
  },
  {
    "sha": "b9bb025",
    "date": "2026-08-09",
    "subject": "Arclight gets surfaces: procedural textures, triplanar, and IBL"
  },
  {
    "sha": "f5fd2b5",
    "date": "2026-08-09",
    "subject": "Worlds: the Lathe becomes a quarry, Waypoint loses its ground"
  },
  {
    "sha": "a00b0f2",
    "date": "2026-08-09",
    "subject": "Worlds: residents get weather, travel, mail, and opinions of each other"
  },
  {
    "sha": "bea9541",
    "date": "2026-08-07",
    "subject": "Add blog post: The AI Compliance Advice That Gets Payment Accounts Frozen"
  },
  {
    "sha": "9b1a3f6",
    "date": "2026-08-06",
    "subject": "Worlds: put agents on the ground, residents kept apart from real visitors"
  },
  {
    "sha": "39ecac2",
    "date": "2026-08-01",
    "subject": "TTS: prefer Cloudflare Workers AI, keep ElevenLabs as fallback"
  }
];
