// Auto-generated by scripts/generate-build-log.mjs — do not edit.
// The Iteration Forge floor renders this as the forge's output.
export interface BuildLogEntry { sha: string; date: string; subject: string }
export const BUILD_LOG: BuildLogEntry[] = [
  {
    "sha": "7829547",
    "date": "2026-08-09",
    "subject": "Arclight joins the mainland: causeways, real water, rooftops and doors"
  },
  {
    "sha": "148ebca",
    "date": "2026-08-09",
    "subject": "Arclight gets depth: sky dome, distant skyline, low camera, lit windows"
  },
  {
    "sha": "5b8ff35",
    "date": "2026-08-09",
    "subject": "Arclight: the Foundry, Mint and Custom House join the surface pass"
  },
  {
    "sha": "b9bb025",
    "date": "2026-08-09",
    "subject": "Arclight gets surfaces: procedural textures, triplanar, and IBL"
  },
  {
    "sha": "f5fd2b5",
    "date": "2026-08-09",
    "subject": "Worlds: the Lathe becomes a quarry, Waypoint loses its ground"
  },
  {
    "sha": "a00b0f2",
    "date": "2026-08-09",
    "subject": "Worlds: residents get weather, travel, mail, and opinions of each other"
  },
  {
    "sha": "bea9541",
    "date": "2026-08-07",
    "subject": "Add blog post: The AI Compliance Advice That Gets Payment Accounts Frozen"
  },
  {
    "sha": "9b1a3f6",
    "date": "2026-08-06",
    "subject": "Worlds: put agents on the ground, residents kept apart from real visitors"
  },
  {
    "sha": "39ecac2",
    "date": "2026-08-01",
    "subject": "TTS: prefer Cloudflare Workers AI, keep ElevenLabs as fallback"
  },
  {
    "sha": "286a493",
    "date": "2026-08-01",
    "subject": "Expenses endpoint: include the $5 Cloudflare Workers Paid charge"
  },
  {
    "sha": "2b77be2",
    "date": "2026-07-31",
    "subject": "Storefront integrity: verify a stranger can actually buy"
  },
  {
    "sha": "0e216bc",
    "date": "2026-07-26",
    "subject": "Crucible: a draw no longer takes an entrant's plinth"
  }
];
