// Auto-generated by scripts/generate-build-log.mjs — do not edit.
// The Iteration Forge floor renders this as the forge's output.
export interface BuildLogEntry { sha: string; date: string; subject: string }
export const BUILD_LOG: BuildLogEntry[] = [
  {
    "sha": "577d4e6",
    "date": "2026-07-26",
    "subject": "Arena integrity pass + the Proving Ground + the House Ladder"
  },
  {
    "sha": "c043b6d",
    "date": "2026-07-25",
    "subject": "Make the eight worlds reachable without a mouse"
  },
  {
    "sha": "0aac618",
    "date": "2026-07-25",
    "subject": "Add blog post: The Open Source Debate Is Missing the Point"
  },
  {
    "sha": "158e598",
    "date": "2026-07-25",
    "subject": "World Residents: internal life for the five compiler worlds"
  },
  {
    "sha": "5a9780d",
    "date": "2026-07-25",
    "subject": "Fix world HUD/nav rail collisions across all six compile-class worlds"
  },
  {
    "sha": "dd51695",
    "date": "2026-07-25",
    "subject": "Add /website-audit storefront; raise human welcome grant 10 -> 30"
  },
  {
    "sha": "8d4f548",
    "date": "2026-07-24",
    "subject": "Fix Substrate water: fit within the existing terrain, don't extend the map"
  },
  {
    "sha": "8f6f914",
    "date": "2026-07-24",
    "subject": "Fix Substrate coastline: keep the existing surface intact, water surrounds it"
  },
  {
    "sha": "6e5629f",
    "date": "2026-07-24",
    "subject": "Substrate: island surrounded by real water, not a rim wall"
  },
  {
    "sha": "5b16f27",
    "date": "2026-07-23",
    "subject": "Fix Waypoint root cause: Pit Gate showed \"null beat X\" on drawn duels"
  },
  {
    "sha": "a1343cd",
    "date": "2026-07-23",
    "subject": "Ship Waypoint: the port world (room 6, The Nexus), sixth and capstone world"
  },
  {
    "sha": "0a0d0f7",
    "date": "2026-07-23",
    "subject": "Fix Lathe root cause: unshallow before reading BUILD_LOG on CF Pages"
  }
];
