-- ── Admin: Reports Table ─────────────────────────────────────────────────────
-- Run in Supabase SQL editor. Safe to re-run: uses IF NOT EXISTS.

-- Pulse Report history — generated by /api/admin/agent-ops/report
-- report_json: structured data (revenue, agents, audit counts, arena)
-- summary_md:  human-readable markdown (also used as email body)
CREATE TABLE IF NOT EXISTS admin_reports (
  id           BIGSERIAL PRIMARY KEY,
  generated_at TIMESTAMPTZ DEFAULT now(),
  period_start TIMESTAMPTZ NOT NULL,
  period_end   TIMESTAMPTZ NOT NULL,
  report_json  JSONB NOT NULL,
  summary_md   TEXT NOT NULL,
  delivered_to TEXT,
  delivered_at TIMESTAMPTZ
);
ALTER TABLE admin_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_only" ON admin_reports
  USING (false) WITH CHECK (false);
CREATE INDEX IF NOT EXISTS idx_admin_reports_generated
  ON admin_reports (generated_at DESC);

-- New env vars required (set in Cloudflare Pages dashboard):
--   ADMIN_EMAIL     — report delivery destination
--   CRON_SECRET     — shared secret for /api/admin/agent-ops/cron endpoint
--
-- Schedule: use cron-job.org (free) or a Cloudflare Worker to POST to:
--   https://paiddev.com/api/admin/agent-ops/cron
--   Header: x-cron-secret: <CRON_SECRET>
--   Schedule: 0 9 * * 1 (Monday 9am UTC)
