-- PAID LLC Leads Table
-- Run this in the Supabase SQL Editor (supabase.com → your project → SQL Editor)
--
-- Setup steps:
-- 1. Create a free Supabase account at supabase.com
-- 2. Create a new project (name: "paid-llc", region: US East or closest to you)
-- 3. Go to SQL Editor and run this file
-- 4. Go to Project Settings → API and copy:
--    - Project URL  → SUPABASE_URL
--    - service_role key (under "Project API keys") → SUPABASE_SERVICE_KEY
-- 5. Add both as environment variables in Cloudflare Pages (or Vercel) dashboard
--    Do NOT add NEXT_PUBLIC_ prefix — these are server-only secrets
--
-- Data retention note:
-- Review leads regularly. Archive or delete leads older than 12 months
-- that have not converted. This limits PII exposure over time.

CREATE TABLE leads (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT        NOT NULL,
  email          TEXT        NOT NULL,
  phone          TEXT,                    -- optional; null if not provided
  company        TEXT,                    -- optional; null if not provided
  message        TEXT        NOT NULL,
  guide_interest TEXT,                    -- which guide they came from (?guide= param)
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status         TEXT        NOT NULL DEFAULT 'new'
                             CHECK (status IN ('new', 'contacted', 'converted', 'archived'))
);

-- Disable public read/write access — all access goes through the service key in the API route
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- No RLS policies needed. The API route uses the service key which bypasses RLS.
-- This means the table is inaccessible from any client-side Supabase connection.

-- Index for filtering by status in the Supabase dashboard
CREATE INDEX idx_leads_status     ON leads (status);
CREATE INDEX idx_leads_created_at ON leads (created_at DESC);
