/**
 * Custom Cloudflare Pages build pipeline.
 *
 * Replaces `npx @cloudflare/next-on-pages` directly because that tool does not
 * propagate `export const runtime="edge"` from not-found.tsx into the Vercel
 * output function config in Next.js 15.5.2. We work around it by:
 *
 *   1. Create .vercel/project.json (same stub @cloudflare/next-on-pages uses)
 *   2. Run `npx vercel build`  (blog data is generated by npm run build inside)
 *   3. Patch _not-found.func/.vc-config.json → runtime=edge
 *   4. Run `npx @cloudflare/next-on-pages --skip-build`
 */
import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function run(cmd) {
  console.log(`\n> ${cmd}`);
  execSync(cmd, { stdio: "inherit", cwd: root });
}

// ── Step 1: create .vercel/project.json stub ──────────────────────────────────
const vercelDir = path.join(root, ".vercel");
const projectJsonPath = path.join(vercelDir, "project.json");

if (!fs.existsSync(projectJsonPath)) {
  fs.mkdirSync(vercelDir, { recursive: true });
  fs.writeFileSync(
    projectJsonPath,
    JSON.stringify({ projectId: "_", orgId: "_", settings: { framework: "nextjs" } })
  );
  console.log("Created .vercel/project.json stub");
}

// ── Step 2: vercel build ──────────────────────────────────────────────────────
// PINNED, not @latest: vercel 54.20.0/54.20.1 (both released 2026-07-03) broke
// output mapping for prerendered routes ("Unable to find lambda for route:
// ..."), which failed every Cloudflare Pages deploy after the morning of
// 2026-07-03 while the repo was unchanged. 54.19.0 (2026-07-02) is the last
// release before the regression. Bump deliberately, never implicitly.
run("npx vercel@54.19.0 build");

// ── Step 3: patch _not-found.func/.vc-config.json ────────────────────────────
const functionsDir = path.join(root, ".vercel", "output", "functions");
const notFoundDir = path.join(functionsDir, "_not-found.func");
const notFoundConfig = path.join(notFoundDir, ".vc-config.json");

// Diagnostic: list all .func directories so the build log shows what was generated
if (fs.existsSync(functionsDir)) {
  const funcs = fs.readdirSync(functionsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name.endsWith(".func"))
    .map((e) => e.name);
  console.log(`patch: found ${funcs.length} .func directories:`, funcs.slice(0, 10).join(", ") + (funcs.length > 10 ? " ..." : ""));
} else {
  console.error("patch: ERROR — .vercel/output/functions/ does not exist. vercel build may have failed.");
  process.exit(1);
}

if (fs.existsSync(notFoundDir)) {
  const notFoundJsFiles = fs.readdirSync(notFoundDir).filter((f) => f.endsWith(".js"));
  console.log("patch: _not-found.func contents →", notFoundJsFiles);

  if (notFoundJsFiles.length === 0) {
    // Empty func directory — @cloudflare/next-on-pages can't bundle it.
    // Delete it so the tool falls back to the prerendered static version.
    fs.rmSync(notFoundDir, { recursive: true });
    console.log("patch: deleted empty _not-found.func/ — /_not-found will be served as static prerender");
  } else {
    const current = fs.existsSync(notFoundConfig)
      ? JSON.parse(fs.readFileSync(notFoundConfig, "utf8"))
      : null;

    console.log("patch: current .vc-config.json runtime →", current?.runtime);

    if (current?.runtime !== "edge") {
      let template = null;
      for (const entry of fs.readdirSync(functionsDir, { withFileTypes: true })) {
        if (!entry.isDirectory() || !entry.name.endsWith(".func") || entry.name === "_not-found.func") continue;
        const cfgPath = path.join(functionsDir, entry.name, ".vc-config.json");
        if (!fs.existsSync(cfgPath)) continue;
        const cfg = JSON.parse(fs.readFileSync(cfgPath, "utf8"));
        if (cfg.runtime === "edge") {
          template = cfg;
          console.log(`patch: using ${entry.name} as edge config template`);
          break;
        }
      }

      if (!template) {
        console.log("patch: no edge template found — using minimal edge config");
      }

      const entrypoint = notFoundJsFiles.find((f) => f === "index.js") ?? notFoundJsFiles[0];
      const patched = template ? { ...template, entrypoint } : { runtime: "edge", entrypoint };
      fs.writeFileSync(notFoundConfig, JSON.stringify(patched, null, 2));
      console.log(`patch: wrote runtime=edge, entrypoint=${entrypoint}`);
    } else {
      console.log("patch: already edge — no change needed");
    }
  }
} else {
  console.log("patch: _not-found.func/ not found — /_not-found is prerendered static");
}

// ── Step 4: @cloudflare/next-on-pages conversion ─────────────────────────────
// --experimental-minify: more aggressive dead-code elimination on the output
// Worker script. Added 2026-07-06 after a deploy hit Cloudflare's 3 MiB free-
// plan Worker size cap (next-on-pages bundles the whole site into one
// combined Worker, not per-route — this is the one safe, code-untouched
// lever available; if it isn't enough, the size growth is aggregate across
// many past features, not one new file, and needs either the CF Workers
// Paid plan (10 MiB cap) or real bundle-size investigation).
// --custom-entrypoint: TEMPORARY diagnostic wrapper (worker-entry.js) that
// captures console.error output on 5xx responses and ships it to Supabase
// Storage — the only way to read the world-route render error without
// Cloudflare log access. Remove with worker-entry.js once root-caused.
run("npx @cloudflare/next-on-pages --skip-build --experimental-minify --custom-entrypoint ./worker-entry.js");

// ── Step 5: repair missing chunk bindings (next-on-pages dedup bug) ──────────
// next-on-pages' chunk dedup replaces a shared webpack chunk code block with a
// bare identifier (e.g. async__chunk_82704) and prepends an import + extraction
// (`const async__chunk_82704 = __exportsOfX["async__chunk_82704"];`) — but in
// some function files the import never lands, and that route 500s at SSR
// require time with "ReferenceError: async__chunk_N is not defined". Which
// function draws the missing binding reshuffles every build (observed live
// 2026-07-20 breaking 1-3 of the four Latent Space world routes per build;
// --disableChunksDedup avoids it but blows the 10 MiB publish cap).
//
// This pass replays the tool's own emit for the bindings it forgot: scan each
// built function for unquoted chunk identifiers with no declaration, find the
// dist file that registers that key, and inject the same import + extraction
// pattern the healthy functions have. If a binding cannot be resolved, FAIL
// the build — a failed deploy keeps the last good build live, which beats
// silently shipping a route that 500s.
const nopDistDir = path.join(root, ".vercel", "output", "static", "_worker.js", "__next-on-pages-dist__");
const nopFunctionsDir = path.join(nopDistDir, "functions");

function* walkJs(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walkJs(p);
    else if (entry.name.endsWith(".js")) yield p;
  }
}

if (fs.existsSync(nopFunctionsDir)) {
  // Index which dist file registers each chunk key, and its export name.
  const providers = new Map();
  for (const entry of fs.readdirSync(nopDistDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === "functions") continue;
    for (const file of walkJs(path.join(nopDistDir, entry.name))) {
      const src = fs.readFileSync(file, "utf8");
      const exp =
        src.match(/export\s+const\s+(\w+)\s*=/) ||
        src.match(/export\s*\{\s*\w+\s+as\s+(\w+)\s*\}/) ||
        src.match(/export\s*\{\s*(\w+)\s*\}/);
      if (!exp) continue;
      for (const m of src.matchAll(/\[\s*["']((?:async)?__chunk_\d+)["']\s*\]\s*=/g)) {
        if (!providers.has(m[1])) providers.set(m[1], { file, exportName: exp[1] });
      }
    }
  }

  let repairedCount = 0;
  const unresolved = [];
  for (const file of walkJs(nopFunctionsDir)) {
    let src = fs.readFileSync(file, "utf8");
    const used = new Set(
      [...src.matchAll(/(^|[^\w$"'])((?:async)?__chunk_\d+)\b(?!["'])/g)].map((m) => m[2])
    );
    const missing = [...used].filter(
      (id) => !new RegExp(`(?:const|var|let)\\s+${id}\\s*=`).test(src)
    );
    if (missing.length === 0) continue;

    const proxyM = src.match(
      /(?:const|var|let)\s+(\w+)\s*=\s*globalThis\.__nextOnPagesRoutesIsolation\.getProxyFor\((?:"[^"]*"|'[^']*')\)\s*;?/
    );
    if (!proxyM) {
      unresolved.push(`${path.relative(nopDistDir, file)}: no proxy declaration; missing ${missing.join(", ")}`);
      continue;
    }
    const proxyVar = proxyM[1];
    const insertAt = src.indexOf(proxyM[0]) + proxyM[0].length;

    const byProvider = new Map();
    for (const id of missing) {
      const provider = providers.get(id);
      if (!provider) {
        unresolved.push(`${path.relative(nopDistDir, file)}: no provider registers ${id}`);
        continue;
      }
      if (!byProvider.has(provider.file)) byProvider.set(provider.file, { exportName: provider.exportName, ids: [] });
      byProvider.get(provider.file).ids.push(id);
    }
    if (byProvider.size === 0) continue;

    let imports = "";
    let extractions = "";
    let ri = 0;
    for (const [providerFile, { exportName, ids }] of byProvider) {
      const rel = path.relative(path.dirname(file), providerFile).split(path.sep).join("/");
      const relPath = rel.startsWith(".") ? rel : `./${rel}`;
      const fnAlias = `__nopRepairGet_${ri}`;
      const objAlias = `__nopRepairExports_${ri}`;
      ri++;
      imports += `import { ${exportName} as ${fnAlias} } from '${relPath}';\n`;
      extractions +=
        `const ${objAlias} = ${fnAlias}(${proxyVar}, ${proxyVar}, ${proxyVar});` +
        ids.map((id) => `const ${id} = ${objAlias}["${id}"];`).join("") +
        "\n";
      console.log(`repair: ${path.relative(nopDistDir, file)} — injecting ${ids.join(", ")} from ${path.basename(providerFile)}`);
    }
    src = imports + src.slice(0, insertAt) + "\n" + extractions + src.slice(insertAt);
    fs.writeFileSync(file, src);
    repairedCount++;
  }

  console.log(`repair: ${repairedCount} function file(s) repaired, ${providers.size} chunk keys indexed.`);
  if (unresolved.length > 0) {
    console.error("repair: UNRESOLVED chunk bindings — failing the build rather than shipping 500s:\n" + unresolved.join("\n"));
    process.exit(1);
  }
} else {
  console.error("repair: ERROR — __next-on-pages-dist__/functions not found; skipping repair.");
  process.exit(1);
}
