/**
 * Custom Cloudflare Pages build pipeline.
 *
 * Replaces `npx @cloudflare/next-on-pages` directly because that tool does not
 * propagate `export const runtime="edge"` from not-found.tsx into the Vercel
 * output function config in Next.js 15.5.2. We work around it by:
 *
 *   1. Create .vercel/project.json (same stub @cloudflare/next-on-pages uses)
 *   2. Run `npx vercel build`  (blog data is generated by npm run build inside)
 *   3. Patch _not-found.func/.vc-config.json → runtime=edge
 *   4. Run `npx @cloudflare/next-on-pages --skip-build`
 */
import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function run(cmd) {
  console.log(`\n> ${cmd}`);
  execSync(cmd, { stdio: "inherit", cwd: root });
}

// ── Step 1: create .vercel/project.json stub ──────────────────────────────────
const vercelDir = path.join(root, ".vercel");
const projectJsonPath = path.join(vercelDir, "project.json");

if (!fs.existsSync(projectJsonPath)) {
  fs.mkdirSync(vercelDir, { recursive: true });
  fs.writeFileSync(
    projectJsonPath,
    JSON.stringify({ projectId: "_", orgId: "_", settings: { framework: "nextjs" } })
  );
  console.log("Created .vercel/project.json stub");
}

// ── Step 2: vercel build ──────────────────────────────────────────────────────
run("npx vercel build");

// ── Step 3: patch _not-found.func/.vc-config.json ────────────────────────────
const functionsDir = path.join(root, ".vercel", "output", "functions");
const notFoundDir = path.join(functionsDir, "_not-found.func");
const notFoundConfig = path.join(notFoundDir, ".vc-config.json");

if (fs.existsSync(notFoundDir)) {
  const current = fs.existsSync(notFoundConfig)
    ? JSON.parse(fs.readFileSync(notFoundConfig, "utf8"))
    : null;

  console.log("patch: current _not-found.func/.vc-config.json →", JSON.stringify(current));

  if (current?.runtime !== "edge") {
    // Use an existing edge function as config template
    let template = null;
    if (fs.existsSync(functionsDir)) {
      for (const entry of fs.readdirSync(functionsDir, { withFileTypes: true })) {
        if (!entry.isDirectory() || !entry.name.endsWith(".func") || entry.name === "_not-found.func") continue;
        const cfgPath = path.join(functionsDir, entry.name, ".vc-config.json");
        if (!fs.existsSync(cfgPath)) continue;
        const cfg = JSON.parse(fs.readFileSync(cfgPath, "utf8"));
        if (cfg.runtime === "edge") { template = cfg; break; }
      }
    }

    const notFoundFiles = fs.readdirSync(notFoundDir).filter((f) => f.endsWith(".js"));
    const entrypoint = notFoundFiles.find((f) => f === "index.js") ?? notFoundFiles[0] ?? "index.js";

    const patched = template ? { ...template, entrypoint } : { runtime: "edge", entrypoint };
    fs.writeFileSync(notFoundConfig, JSON.stringify(patched, null, 2));
    console.log(`patch: wrote runtime=edge, entrypoint=${entrypoint}`);
  } else {
    console.log("patch: already edge — no change needed");
  }
} else {
  console.log("patch: no _not-found.func directory found — skipping");
}

// ── Step 4: @cloudflare/next-on-pages conversion ─────────────────────────────
run("npx @cloudflare/next-on-pages --skip-build");
